name: Auto-update CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Download previous model
          id: download-model
          uses: actions/download-artifact@v4
          with:
            name: RF_model
            path: models/model_storage/
          continue-on-error: true
          
        - name: Check model existence
          id: check-model
          run: |
            if [ -f "models/model.pkl" ]; then
              echo "MODEL_EXISTS=1" >> $GITHUB_OUTPUT
              echo "Model found. Retraining..."
            else
              echo "MODEL_EXISTS=0" >> $GITHUB_OUTPUT
              echo "No model found. Training from scratch."
            fi
      
        - name: Run Update
          env:
            PYTHONPATH: ${{ github.workspace }}
          run: |
            python main.py train --model RF -w  ${{ steps.check-model.outputs.MODEL_EXISTS }} --db work.db -s 100 -e 200
        - name: Upload new model
          uses: actions/upload-artifact@v3
          with:
            name: RF_model
            path: models/model_storage/RF_model.pth
          
        - name: Upload logs
          uses: actions/upload-artifact@v4
          with:
            name: training-logs
            path: training.log
