name: Auto-update CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Download previous model
          uses: actions/download-artifact@v3
          with:
            name: RF_model
            path: models/model_storage/
      
        - name: Run Update
          env:
            PYTHONPATH: ${{ github.workspace }}
          run: |
            python main.py train --model RF -w 1 --db work.db -s 100 -e 200
        - name: Upload new model
          uses: actions/upload-artifact@v3
          with:
            name: RF_model
            path: models/model_storage//RF_model.pth
          
        - name: Upload logs
          uses: actions/upload-artifact@v4
          with:
            name: training-logs
            path: training.log
