name: ML CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Update
          env:
            PYTHONPATH: ${{ github.workspace }}
          run: |
            python train --model RF -w 1 --db work.db -s 100 -e 200
        - name: Upload logs
          uses: actions/upload-artifact@v4
          with:
            name: training-logs
            path: training.log
